spring:
  application:
    name: lojahub
  datasource:
    url: jdbc:mysql://localhost:3306/lojahub
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled : true
      force : true